### ISSUE TITLE
Issues with the XSS Module

### ISSUE THREAD

**Issue by 419066074** [coffinxp/loxs#1]
Hello author,

This program encounters issues when running the XSS module on M-series Macs because it does not identify the system architecture and defaults to downloading the x86 version of chromedriver, which causes runtime errors. I hope you can add a check to identify the architecture.

Currently, I have managed to run it by specifying the chromedriver executable path as follows: service = ChromeService(executable_path='./chromedriver').

**Comment by coffinxp** [comment]
sure we will fix that soon we only tested on  linux invironment but soon make compatible for all os..
