### ISSUE TITLE
error execution 

### ISSUE THREAD

**Issue by nullsecX270** [coffinxp/loxs#10]
![Capture d’écran 2024-09-17 210237](https://github.com/user-attachments/assets/e4408b78-e8cd-4c35-8d56-ace0c91b947c)

**Comment by Meet46** [comment]
what this video:- https://www.youtube.com/watch?v=w5GHj7vKFYM

**Comment by ghost** [comment]
Hello

I fixed this issue, can you confirm?

**Comment by nullsecX270** [comment]
thanks guys

**Comment by ghost** [comment]
thanks for your feedback ;) 
have a good day
