### ISSUE TITLE
ZeroDivisionError : Exception on 0 vulnerable URLs Report Generation 

### ISSUE THREAD

**Issue by viralvaghela** [coffinxp/loxs#21]
Hello @coffinxp 

When there is a 0 vulnerable URL found and trying to generate the HTML report, code is throwing the ZeroDivisonError 
```py
  File "/home/kali/Desktop/tools/lostools/loxs.py", line 335, in generate_html_report
    width: {(total_found / total_scanned) * 100}%;
             ~~~~~~~~~~~~^~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```
Maybe adding a try catch block to handle this case should fix the issue, or i can work on this if you would like to assign it to me, would be happy to contribute :)

**Comment by coffinxp** [comment]
ok we will fix.but i don'nt think someone will generate report of 0 found !
