### ISSUE TITLE
Not working on some urls

### ISSUE THREAD

**Issue by xskullboyx** [coffinxp/loxs#3]
xss url:
https://brutelogic.com.br/lab/inside-handler.php?p=%26apos;-alert(1)-%26apos;

result:
![Screenshot from 2024-09-14 06-11-23](https://github.com/user-attachments/assets/b8f4411d-e134-4036-b956-dd910f5f2374)

**Comment by coffinxp** [comment]
maybe this url is not vulnerable or show me if it is by which payload
