### ISSUE TITLE
Empty Output when running "filter.sh"

### ISSUE THREAD

**Issue by PiyushThePal** [coffinxp/loxs#30]
I have installed all the tools but even output for "tesla.com" is empty.

<img width="900" alt="Screenshot 2024-10-17 at 8 18 25 PM" src="https://github.com/user-attachments/assets/e1aa6b5c-5fb9-4877-85e7-f713716d4819">

**Comment by coffinxp** [comment]
some site block active crawling so make sure test it by using oneliner..
