### ISSUE TITLE
no progress!

### ISSUE THREAD

**Issue by d3adb0d7** [coffinxp/loxs#33]
![image](https://github.com/user-attachments/assets/3a1f1ed4-4759-4b19-a816-bea6d364b3c2)
no progress!

**Comment by ghost** [comment]
Hello,

Everything works on my side, make sure you install all libraries, chromedriver ...

What setting did you use for threads and timeout ? | try using the default setting

hexsh1dow

**Comment by d3adb0d7** [comment]
xss not working. its stucked.

**Comment by ghost** [comment]
Hello,

1. don't run with root permission

2. Make sure to install all requirements :

--> pip install -r requirements.txt

3. If it still doesn't work, reinstall ChromeDriver

hexsh1dow

**Comment by CyberPro010** [comment]
man i had this issue too just run in normal user instead root it fixs

**Comment by CyberPro010** [comment]
make sure your things are updated and installed
