### ISSUE TITLE
Open Redirect Error

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [coffinxp/loxs#37]
I have these on my server:
```
root@mini:~# google-chrome --version
Google Chrome 130.0.6723.58 
root@mini:~# chromedriver --version
ChromeDriver 129.0.6668.100 (cf58cba358d31ce285c1970a79a9411d0fb381a5-refs/branch-heads/6668@{#1704})
root@mini:~# 
```
However, OR scanner, shows me this

![image](https://github.com/user-attachments/assets/79df42cf-5cb7-443f-b28e-a1b892413c0d)

**Comment by coffinxp** [comment]
your prompt is root chrome not work as root so use it as a normal user

**Comment by Sh4d0wHunt3rX** [comment]
Thanks @coffinxp , I debugged the issue more with the help of ChatGPT.

I created this python file and ran it:

```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

options = webdriver.ChromeOptions()
options.add_argument('--headless')  # For running without UI
options.add_argument('--no-sandbox')  # Required in some environments
options.add_argument('--disable-dev-shm-usage')  # Prevents issues with /dev/shm in Docker

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
driver.get("http://www.google.com")
print(driver.title)
driver.quit()
```
I got this:

```
root@mini:~# python3 test.py
Traceback (most recent call last):
  File "/root/test.py", line 10, in <module>
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/local/bin/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  ```
  Look at the last 3 lines, it's same error.
  
  Then I created this file:
  
  ```
  from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

# Configure Chrome options for headless mode
options = webdriver.ChromeOptions()
options.binary_location = '/usr/bin/google-chrome'  # Update with the path from `which google-chrome`
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--disable-gpu')
options.add_argument('--remote-debugging-port=9222')  # Required for remote debugging in headless mode
options.add_argument('--window-size=1920x1080')
options.add_argument('--disable-software-rasterizer')

# Initialize the Chrome WebDriver with the configured options
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

# Test navigation
driver.get("http://www.google.com")

# Print the page title to verify
print(driver.title)

# Close the browser
driver.quit()
```

Which when I ran, it worked correctly:

```
root@mini:~# python3 test2.py
Google
```

It seems the issue needs to be addressed in the code, not related to root/user.

**Comment by Sh4d0wHunt3rX** [comment]
More insights from ChatGPT:

This error indicates that Chrome failed to start, possibly due to incorrect configuration, or the DevToolsActivePort file could not be created, meaning Chrome could not open properly.

Key Differences Between test.py (Failing) and test2.py (Working):
Binary Location:

test.py did not specify the binary location for Chrome.
test2.py explicitly sets options.binary_location = '/usr/bin/google-chrome'. This ensures Selenium is pointing to the correct path of the Chrome installation.
Additional Chrome Arguments:

test.py only included --headless, --no-sandbox, and --disable-dev-shm-usage.
test2.py added critical flags:
--disable-gpu: This is often required in headless mode to prevent GPU-related issues.
--remote-debugging-port=9222: Allows Chrome to run in headless mode and communicate via a remote debugging port, which can fix issues with the DevToolsActivePort.
--disable-software-rasterizer: Prevents Chrome from using software rendering, which can cause issues on servers without hardware acceleration.
--window-size=1920x1080: Specifies a default window size, which can prevent crashes in headless mode when no display is available.
Why test2.py Fixed the Issue
Correct Chrome Path: The key difference was explicitly specifying the Chrome binary location. The DevToolsActivePort error in test.py may have been caused by Selenium not being able to find the correct Chrome binary. By specifying the correct path (/usr/bin/google-chrome), test2.py ensures that the Chrome browser is launched correctly.

Remote Debugging Port: The addition of --remote-debugging-port=9222 in test2.py resolves the DevToolsActivePort issue. This option allows Chrome to run in headless mode while still allowing communication between Selenium and the browser.

Full Set of Options: The other flags (like --disable-gpu, --window-size, and --disable-software-rasterizer) in test2.py provide a more robust configuration, ensuring Chrome runs smoothly in headless mode, even in constrained environments (such as servers with limited resources or without a display).

Conclusion:
The main causes of the fix were:

Explicitly setting the correct Chrome binary path in test2.py (/usr/bin/google-chrome).
Adding the --remote-debugging-port=9222 to resolve communication issues between Selenium and Chrome in headless mode.
Including additional options to ensure Chrome could run smoothly on a headless Ubuntu server.

**Comment by coffinxp** [comment]
thnq so much for this now check the code loxs.py all updated and send me your feedback.

**Comment by Sh4d0wHunt3rX** [comment]
Thanks a lot @coffinxp , this is what I got now with new update:

![image](https://github.com/user-attachments/assets/c39ec2d7-cf50-4508-94da-d0296f7fd4e2)
![image](https://github.com/user-attachments/assets/50805df4-1a89-46ea-880b-6c4f1b666b26)

**Comment by Sh4d0wHunt3rX** [comment]
Hey @coffinxp , I appreciate if you can re-open this issue, thanks : )
