### ISSUE TITLE
tool update problem

### ISSUE THREAD

**Issue by erkankavas** [coffinxp/loxs#40]
get this messsage
i think need to show own folder.

[!] The directory specified in config.yml does not exist: /home/coffinxp/lostools

**Comment by erkankavas** [comment]
after edit config.yml with my older root. it is okey.

**Comment by 1hehaq** [comment]
> get this messsage i think need to show own folder.
> 
> [!] The directory specified in config.yml does not exist: /home/coffinxp/lostools

You're likely using an outdated version of **LOXS**. Please reinstall **LOXS** to resolve this. Once updated, future updates can be applied directly using option 6 in the main menu, without needing to reinstall.
