### ISSUE TITLE
not a issue but thanks

### ISSUE THREAD

**Issue by CyberPro010** [coffinxp/loxs#43]
i mean really thanks from my heart like i am so stupid i ran on normal user and my xss problem is fixed so thanks now i can hunt bugs more happily so i suggest to not remove this issue so people can see how good your at problem solving ; )

**Comment by ghost** [comment]
Hey, 

Glad to see your problem is resolved )) 

I'll keep this open ;)

Happy hunting !
hexsh1dow

**Comment by CyberPro010** [comment]
you guys are so polite man appreciate that
