### ISSUE TITLE
Chrome driver issue

### ISSUE THREAD

**Issue by Aman-Tris102** [coffinxp/loxs#45]
![Screenshot 2024-10-26 190153](https://github.com/user-attachments/assets/c5cde0eb-ddc4-483b-a4a7-87a2fd33da8b)

Why do i get this error ? How do i fix it

**Comment by ghost** [comment]
Hello,

Make sure to install all requirements :

--> pip install -r requirements.txt

If it still doesn't work, reinstall ChromeDriver

Also don't run with root permission

hexsh1dow
