### ISSUE TITLE
XSS works, but OR does not work, gives an error DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by Remourz** [coffinxp/loxs#47]
Hello

When using the tool, i'm getting errors for the OR section (see image)
![image](https://github.com/user-attachments/assets/cf47d110-02fa-4c41-b745-c93f8f9db5ac)

But the strange part is, the XSS section is working fine

**Comment by 1hehaq** [comment]
Hello,

We’ve encountered this issue before. For now, please try running it as a non root user.

Best regards,
Haq
