### ISSUE TITLE
Tab crashed error in XSS hunter

### ISSUE THREAD

**Issue by moin-gun** [coffinxp/loxs#49]
I appreciate efforts of all the contributors of the tool. Kindly help me resolve the error I have attached. 
I had followed all the steps to install chrome and chromedriver but I can't figure out.

![image](https://github.com/user-attachments/assets/770a7868-dc01-4e62-a656-3e5b474fb0c5)

**Comment by 1hehaq** [comment]
Hello,

Sorry for the late response, Can you try to run the OR scanner as non root user please...

we will try to resolve the issue. Let you know after patches 

Regards <3

**Comment by moin-gun** [comment]
Thank you @1hehaq for your response. 

I am facing same error message with non-root user.

![image](https://github.com/user-attachments/assets/1911c7b9-16f4-43e0-a827-c38a1828b19a)

**Comment by ghost** [comment]
Hey,

Make sure to install all requirements :

--> pip install -r requirements.txt

If it still doesn't work, reinstall ChromeDriver ( check the readme file) -> it may due to that

If it still doesn't working and If you are not on linux, try on linux 

hexsh1dow

**Comment by moin-gun** [comment]
Hi,

I ran `pip install -r requirements.txt` 2 times.
I reinstalled chrome driver 2 times.
I am working on Debian Linux, a droplet of digitalOcean. Here is my system info: Linux <HOST_NAME> 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux

I am still facing the same error as above, kindly help.

Thanks

**Comment by moin-gun** [comment]
Hi @1hehaq and @HexShad0w, I would really appreciate your inputs on how to fix this?

Thanks

**Comment by ghost** [comment]
Hey,

So yeah, normally this issue occurs due to these three points: requirements, ChromeDriver, and running as root.

However, as you mentioned, it still doesn't seem to be working.

Can you try creating a virtual environment in Python? Follow these steps; it should work 🤞

1. Install virtualenv (if it’s not already installed):

pip install virtualenv

2. Create a Virtual Environment: 

python3 -m venv venv

3. Activate the Virtual Environment:

source venv/bin/activate

You should now see the virtual environment name in your terminal prompt.

4. Install Requirements:

pip install -r requirements.txt

5. Run the script (without root privileges):

python3 loxs.py


Hope this will work for you 🤞
Also sorry fot the delay 

hexsh1dow

**Comment by moin-gun** [comment]
Dear @HexShad0w , If you see my screenshot you can see that I am already running the tool in a virtual environment 'myenv' and still I again tried just now with non-root user but still facing same message stating 'Tab crashed'.
Could you please try to reproduce the issue by creating a fresh new droplet with Debian from digital Ocean?

**Comment by ghost** [comment]
Hi,

Oh yeah, I didn't check all the screenshot ... 

Hmm yeah, I'll try to reproduce your issue and tell you then

hexsh1dow

**Comment by ghost** [comment]
Update :

On the code comment this line :

chrome_options.add_argument("--headless") -> line 950

hexsh1dow

**Comment by 1hehaq** [comment]
Hello @moin-gun 

**Please try this script:** [loxs.zip](https://github.com/user-attachments/files/17611557/loxs.zip)

**Comment by moin-gun** [comment]
After commenting option of headless, this is the error what I am facing now.

![image](https://github.com/user-attachments/assets/6004a65d-3caf-4bbe-a27b-07925d7d369a)


I went through tons of stackoverflow and other forums but I can't figure out, I am on the edge of giving up now.
My chrome driver version is 128.0.6613.119 therefore I installed google-chrome with the exact same version but still no luck :(

You guys take your time to figure out, I know y'all are busy and I am spamming your inbox again. I'll wait for your response if there's any working solution. 

Thanks both @1hehaq @HexShad0w for your support till now.

**Comment by CyberPro010** [comment]
my just don't run xss scan

**Comment by moin-gun** [comment]
@CyberPro010 are you running the tool locally or cloud server?

**Comment by ghost** [comment]
Hello @moin-gun,

Apologies for the delay.

The issue might be due to your ChromeDriver version. 

You can find the ChromeDriver link to download it directly in the README file. Make sure to place it in your /bin folder.

Normally, this should work.

hexsh1dow

**Comment by moin-gun** [comment]
I am using the latest version of chrome.
`Google Chrome 130.0.6723.116`

I request you to kindly tell me what version of google chrome and chrome driver you all people use? 
I don't know if my RAM is the issue but I am using 512 MB RAM machine. I will try to upgrade it to 1 GB and try again.

**Comment by moin-gun** [comment]
Hi @HexShad0w @1hehaq @coffinxp 

Latest update: This is working now, the issue was XSS scanner requires minimum 1 GB RAM and I had only 512 MB RAM. You can update this one line instruction in README so no one else has to go through this mess again. 

Thanks all for your support and for providing amazing tools for free. Closing this issue now.

Moin

**Comment by mohammed19990** [comment]
[moin-gun](https://github.com/moin-gun) hi did you Fix the proplem or what?

**Comment by moin-gun** [comment]
Hi @mohammed19990 yes it got resolved. XSS scanner requires minimum 1 GB RAM to run.

**Comment by reedA201** [comment]
> Hi @mohammed19990 yes it got resolved. XSS scanner requires minimum 1 GB RAM to run.

how did you resolved? 
my RAM 4G?
