### ISSUE TITLE
Tool unable to detect XSS

### ISSUE THREAD

**Issue by souilos** [coffinxp/loxs#50]
Am I doing something wrong? Looking for help, I am sure I am not using the tool properly!

<img width="801" alt="Capture d’écran 2024-11-03 à 17 45 22" src="https://github.com/user-attachments/assets/4eeee169-28b6-4a0a-984b-25ab6d0306de">

While the tool cannot detect it (working payload on top of the list).

<img width="614" alt="Capture d’écran 2024-11-03 à 17 50 19" src="https://github.com/user-attachments/assets/eeff823e-8ea5-44cd-8d0e-a3acbbf3e7cb">

**Comment by coffinxp** [comment]
test again after new update !
