### ISSUE TITLE
Add more modules.

### ISSUE THREAD

**Issue by Katastrofa0** [coffinxp/loxs#51]
Hi, realy thx for tool. Will u add some more modules with payloads? Like RFI , SSTI or SSRF etc.. gonna be awesome

**Comment by CyberPro010** [comment]
bro my just xss scan don't run

**Comment by 1hehaq** [comment]
> Hi, realy thx for tool. Will u add some more modules with payloads? Like RFI , SSTI or SSRF etc.. gonna be awesome

Hello @Katastrofa0 ,

Glad to hear such suggestions <3

we are fixing a few small issues with the XSS scanner right now, and then we’ll start on the next module. Which one would you like to see first RFI, SSTI, or SSRF?

Let us know

(We prioritize near to zero false positives, so we will choose the next module based on behavior and logic)
