### ISSUE TITLE
XSS scanner fails to discover injection

### ISSUE THREAD

**Issue by souilos** [coffinxp/loxs#53]
Hey! thanks for the update guys 🙂

I just edited the script for my payloads to not be encoded from xss.txt but it still fails to detect when it's vulnerable...

<img width="986" alt="Capture d’écran 2024-11-04 à 11 03 41" src="https://github.com/user-attachments/assets/134ec130-1bcb-4718-a9b7-03f9592a057a">

<img width="781" alt="Capture d’écran 2024-11-04 à 11 05 13" src="https://github.com/user-attachments/assets/1ba78c39-58b9-4371-bf83-a6ee1ba7335f">

**Comment by HexShad0w** [comment]
Hello, 

The issue is due to the timeout you set, try setting 5 - 10, the default one is for quick scanning, but when the site is a little slow it can cause false negative

Thanks for the feedback 😉

hexsh1dow

**Comment by ghost** [comment]
Hello, 

The problem may be due to the timeout you have set, try setting 5 - 10, the default one is for quick scan, but when the site is a bit slow it may cause false negatives. 

Thank you for your feedback! 

hexsh1dow

**Comment by souilos** [comment]
Hey @HexShad0w thanks for you answer!

The issue is still present even with timeout set at 10... Can we chat on TG so we can fix it? 

The exact same payload is not working with the tool, I am sure it could miss other injections then..

https://t.me/souilos
