### ISSUE TITLE
Crash when running on wsl2

### ISSUE THREAD

**Issue by SNISS** [coffinxp/loxs#55]
File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5644ad9404e3 <unknown>
#1 0x5644ad66fc76 <unknown>

**Comment by coffinxp** [comment]
paste chorme driver in usr/bin and dont run tool in sudo mode bcz chrome dont run as sudo
