### ISSUE TITLE
    from _curses import * ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by TeamSyncOffical** [coffinxp/loxs#56]
from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by ghost** [comment]
Hello,

Make sure to install all requirements :

--> pip install -r requirements.txt

hexsh1dow

**Comment by tajuislam** [comment]
solve this problame

/usr/local/lib/python3.12/dist-packages/requests-2.20.0-py3.12.egg/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (5.2.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/root/loxs/loxs.py", line 60, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager

**Comment by ghost** [comment]
Hello,

Make sure to install/upgrade all requirements :

--> pip install -r requirements.txt

hexsh1dow

**Comment by TeamSyncOffical** [comment]
Issue was that i used windows not kali, will there be windows support ever?

**Comment by ayazxxx** [comment]
@TeamSyncOffical  windows curses package 
pip install windows-curses
it will work correctly.

**Comment by TeamSyncOffical** [comment]
Thanks, I'll check it out.
