### ISSUE TITLE
Option to hide noise

### ISSUE THREAD

**Issue by moin-gun** [coffinxp/loxs#61]
Dear team,

could you please add an option to hide all the noise of "Not vulnerable" URLs.

![image](https://github.com/user-attachments/assets/38a15992-0f41-40b0-bbf4-af678847086d)

**Comment by moin-gun** [comment]
Maybe just display success URL and progress how many payloads were executed like Gobuster and ffuf.

**Comment by coffinxp** [comment]
not user friendly bcz if some sites are not vulnerable then its show nothing and people think its not working so thats why we used verbose so they know its testing the paylaods
