### ISSUE TITLE
Chrome Driver error

### ISSUE THREAD

**Issue by T3chnocr4tX** [coffinxp/loxs#64]
Chrome driver error and have follow all the necessary requirement from the readme file is still not working as intended.

**Comment by Conato1** [comment]
I've already solved this issue using this

first you can delete the .wmd folder and run this command

pip3 uninstall webdriver-manager
pip3 install webdriver-manager

**Comment by T3chnocr4tX** [comment]
thanks man for the reply, i did the necessary steps it is also showing some errors.

![2024-11-25_16-50](https://github.com/user-attachments/assets/66003199-c0b8-49d2-89d1-95ab88575e52)

**Comment by T3chnocr4tX** [comment]
thanks man for the reply, i did the necessary steps it is also showing some
errors.
