### ISSUE TITLE
nothing in the output file 

### ISSUE THREAD

**Issue by Naboot42** [coffinxp/loxs#65]
I have this error when a use filter.sh and nothing is write on the output file 

./filter.sh
Enter the website URL or domain: http://testphp.vulnweb.com/
Normalized URL being used: http://testphp.vulnweb.com/
Running katana with passive sources (waybackarchive, commoncrawl, alienvault)...
./filter.sh: ligne 22: uro : commande introuvable
Running katana actively with depth 5...
./filter.sh: ligne 26: uro : commande introuvable
./filter.sh: ligne 26: anew : commande introuvable

**Comment by coffinxp** [comment]
try using first oneliner and check if its show in terminal or not then use this bash file.sometime its not showing output due to some issue in fetching urls from sources so...also make sure all tools intalled properly used in bash script
