### ISSUE TITLE
Does not find Basic XSS in Altoro Mutual Website

### ISSUE THREAD

**Issue by virgilcj** [coffinxp/loxs#66]
I was testing out the tool with the inbuilt payloads and it did not find anything vulnerable for a while. 
When I manually checked the same URLs and payloads in browser it shows alert prompt. 

Some of the urls below are actually vulnerable and this tool missed everything
![image](https://github.com/user-attachments/assets/a94fd6a2-0d47-43b0-a127-0ed2136d0400)

**Comment by virgilcj** [comment]
Timeout was set to 10 seconds and it still does not find. Dissapointed with the tool.

**Comment by bytes-Knight** [comment]
Hi @virgilcj,

This tool requires a secure HTTPS connection to accurately scan URLs. However, the target website (altoro.testfire.net) seems to be facing SSL/TLS certificate issues.

![Screenshot 2024-11-29 194705](https://github.com/user-attachments/assets/d7ca1255-58d8-4618-955f-87e31ecb7979)

The error NET::ERR_CERT_COMMON_NAME_INVALID indicates a certificate mismatch or misconfiguration. Unfortunately, this prevents the tool from establishing a secure connection, which is essential for accurate scanning and testing.

**Comment by whiteching1999** [comment]
change https to http
