### ISSUE TITLE
Google Chrome issue

### ISSUE THREAD

**Issue by freelancermijan** [coffinxp/loxs#67]
https://github.com/user-attachments/assets/e8c3d35d-66b1-4198-b3c7-e4529f17abba

**Comment by ghost** [comment]
Hello,

It seems the issue might be related to the target URL. Is it a valid parameter ?

Also, take a look at the threads I created yesterday and check for any common issues

Best,
hexsh1dow

**Comment by freelancermijan** [comment]
https://github.com/user-attachments/assets/ba1600e4-94d1-485d-adc7-cf2aab458845

see

**Comment by ghost** [comment]
Hey, 

I may have an idea why you are having this problem 

Does it work with this param?

testphp.vulnweb.com/listproducts.php?cat=1

**Comment by freelancermijan** [comment]
https://github.com/user-attachments/assets/d91fb10a-4ef9-4436-873f-9d0581533272

**Comment by ghost** [comment]
Hi, 

First, take a look at the threads I made yesterday 

Do this first and then tell me

Best, 
hexsh1dow

**Comment by freelancermijan** [comment]
From where I've to check threads? And How? Is it (Enter the timeout duration for each request (Press Enter for 0.5)) your'e taking about? or something else?

**Comment by ghost** [comment]
No, 

I mean the threads I made on X to fix common issues 

Best,
hexsh1dow

**Comment by freelancermijan** [comment]
https://x.com/hexsh1dow/status/1863322915086712910

I'v checked all the things. but still have problem.

**Comment by freelancermijan** [comment]
https://github.com/user-attachments/assets/93abe83e-500c-447b-a655-00ea5fc653ad

I can't run any GUI applications on my wsl 2 system. Can you help me with this?
