### ISSUE TITLE
i get error plz help? 

### ISSUE THREAD

**Issue by 0dayanon** [coffinxp/loxs#69]
whenever i do ./filter.sh to gather url's it gives error and the output files get created 
![image](https://github.com/user-attachments/assets/41c4b221-6597-42c9-b31c-073c8fe490ad)
empty....

**Comment by 1hehaq** [comment]
> whenever i do ./filter.sh to gather url's it gives error and the output files get created 
> ![image](https://github.com/user-attachments/assets/41c4b221-6597-42c9-b31c-073c8fe490ad)
> empty....

Bro, understand the error that shows and try to fix. That's how you grow

And the errors are not with the script or tool, but you dont installed what it requires. You can just read the errors or just copy paste in chatgpt
