### ISSUE TITLE
No module name git

### ISSUE THREAD

**Issue by cyberxploithausa** [coffinxp/loxs#7]
After cloning the repo and installing the `requirements.txt` file, I encounter this error upon running the tool.
```
  File "/home/[pathToFile]/lostools/lostsec.py", line 18, in <module>
    from git import Repo
ModuleNotFoundError: No module named 'git'

```

**Comment by coffinxp** [comment]
pip install gitpython

**Comment by cyberxploithausa** [comment]
> pip install gitpython

Awesome it did work. Thanks
